/*
 * Basics of Computer Graphics Exercise
 *
 * DO NOT EDIT THIS FILE!
 */

#ifndef ASSIGNMENT_H
#define ASSIGNMENT_H

#include "main.h"
#include <gl_core_32.hh>
#include <iostream>

void drawScene(int scene, float runTime);
void initCustomResources();
void deleteCustomResources();
void printStudents();

const glm::vec3 eyePos = glm::vec3(0.0f, 8.0f, 10.0f);
/*
 * Attention:
 * Light source positions are given in eye-space coordinates
 * since they are supposed to remain at a constant position
 * in the scene!
 */
const glm::vec4 vLightPosition = glm::vec4(-2.83, 14.45, -3.89, 1.0f);
const glm::vec3 vLightColor    = glm::vec3(1.0f, 1.0f, 1.0f);

const float fSpecularityExponent = 20.0f;

#endif
