/*
 * Basics of Computer Graphics Exercise
 *
 * DO NOT EDIT THIS FILE!
 */

#ifndef ASSIGNMENT_H
#define ASSIGNMENT_H

#include "main.h"
#include <iostream>

void drawScene(int scene, double);
void drawScenePreview(int scene, double);
void initCustomResources();
void deleteCustomResources();
void printStudents();
void resizeCallback(int newWidth, int newHeight);

/*
 * Attention:
 * Light source positions are given in eye-space coordinates
 * since they are supposed to remain at a constant position
 * in the scene!
 */
const glm::vec3 vLightPosition = glm::vec3(0.0f, 1.0f, 0.0f);
const glm::vec3 vLightColor = glm::vec3(1.0f, 1.0f, 1.0f);

const glm::mat3 mAmbientMaterial =
        glm::mat3(0.2f, 0.0f, 0.0f,
                  0.0f, 0.2f, 0.0f,
                  0.0f, 0.0f, 0.2f);

const glm::mat3 mSpecularMaterial =
        glm::mat3(0.95f, 0.0f, 0.0f,
                  0.0f, 0.95f, 0.0f,
                  0.0f, 0.0f, 0.95f);

const float fSpecularityExponent = 40.0f;

#endif
