/*
 * Basics of Computer Graphics Exercise
 *
 * DO NOT EDIT THIS FILE!
 */

#ifndef ASSIGNMENT_H
#define ASSIGNMENT_H

#include "main.h"
#include <iostream>

void drawScene( int scene, float runTime );
void initCustomResources();
void deleteCustomResources();
void printStudents();
void resizeCallback( int newWidth, int newHeight );

#endif
